artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  unzip_dir: artifacts/data_ingestion
  data_file: artifacts/data_ingestion/data.zip
  source_url: https://github.com/entbappy/Branching-tutorial/raw/master/summarizer-data.zip
